spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/converter
    username: converter_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    listener:
      ack-mode: manual_immediate
    bootstrap-servers: localhost:9092
    consumer:
      group-id: file-converter-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  source-bucket: source-files
  converted-bucket: converted-files

kafka:
  topics:
    input: files.input
    output: files.output